### ISSUE TITLE
[0.79.0.181] Having more than 80oz of flour when making dough causes loss of excess.

### ISSUE THREAD

**Issue by Greyhawk0** [Deadrik/TFCraft#599]
Tested with wheat. About 100oz of wheat flour added to bucket of water gave only 160oz of dough. Expected 160oz dough + 40oz dough or 160oz dough + 20oz flour.

**Comment by dobegor** [comment]
This bug is still reproducable btw.

**Comment by Kittychanley** [comment]
@dobegor Could you please provide the exact steps that you are doing to reproduce the bug? As well as what version of TFC and Forge you are using, and if you are on a server or single player. Because I can't reproduce it. List out everything you do in great detail, including if you are using your mouse to move items, shift-clicking, or pressing hotbar numbers.

**Comment by dobegor** [comment]
@Kittychanley 
TFC Beta 0.79.26.881
MinecraftForge v10.13.4.1558
Forge Mod Loader version 7.99.36.1558

Sorry, might be a false report. 
I guess the problem was that I was using TNFC (modified TFC version for tech pack).
Everything's ok now.

**Comment by dobegor** [comment]
@Kittychanley 
sorry for offtop, but how can I add TFC as dependency in gradle to develop an addon?

**Comment by ADHalek** [comment]
You don't. We don't have a maven, so you'll need to compile a dev copy of the mod yourself and add that to your build path.

**Comment by Kittychanley** [comment]
You don't. We don't have a maven, so you'll need to compile a dev copy of the mod yourself and add that to your build path.
