### ISSUE TITLE
[0.79.19] Client Crash with Equipped Log.

### ISSUE THREAD

**Issue by Bletch1971** [Deadrik/TFCraft#775]
If the player sneak right-clicks a log onto the firepit, the client will crash. The exception is that the TEFirepit cannot be cast as a TELogPile.

I am unsure of how many other blocks this exception will occur on.

I was trying to see if sneaking while right-clicking a log onto a firepit would add the log to the firepit, without opening the firepit GUI. But it crashed instead.

**Comment by Kittychanley** [comment]
Unless the bug is explicitly in a new development version, and not in a released version of the mod, or you know the exact line numbers of where the issue is and are including an explanation of how to resolve the bug, please use the support forum for any reports. This tracker is not for general bug reports. #582
