### ISSUE TITLE
Allow Salad bowl break rate to 0%

### ISSUE THREAD

**Issue by rjdunlap** [Deadrik/TFCraft#808]
We'd like to have a config option to allow us to turn off Salad bowl breaking.
https://github.com/Deadrik/TFCraft/blob/master/src/Common/com/bioxx/tfc/Food/ItemSalad.java#L63

**Comment by Kittychanley** [comment]
This has been discussed extensively on the forums, and for balance reasons the answer is no. We want players to use clay through all tiers of progression. Bowls breaking is one way of implementing this.

**Comment by rjdunlap** [comment]
Players then just use Sandwhiches..

**Comment by Kittychanley** [comment]
It took extensive discussion just to add the 50% config option, and that was only added because we increased the clay cost of making the bowls so in the end the only thing it really saves is straw and logs. It is much easier to leave it as a simple boolean toggle between choices than to add another option into the mix.

The way it is currently set up, that config option doesn't just change how often bowls will break, it also changes the crafting recipe for the bowls. Adding another option to that is just going to make it even more complicated.

**Comment by rjdunlap** [comment]
just our 2 cents
