### ISSUE TITLE
Animals born in walls

### ISSUE THREAD

**Issue by JAWolfe04** [Deadrik/TFCraft#818]
I noticed a little bug where animals spawn in walls, fences, etc.

In an animals OnLivingUpdate method (cow, deer, horse, pig, sheep, wolf), if you set:
baby.setLocationAndAngles(posX + (rand.nextFloat() - 0.5F) * 2F, posY, posZ + (rand.nextFloat() - 0.5F) * 2F, 0.0F, 0.0F);

to

baby.setLocationAndAngles(posX, posY, posZ, 0.0F, 0.0F);

Babies will no longer spawn in walls and instead spawn under the mother. The mother should be in a safe place to spawn. It also simulates the animals coming from the mother and not just spawning around the mother.

**Comment by Kittychanley** [comment]
Have you actually tried doing this? The last time I checked mobs really don't do well when they are immediately on top of each other. Either they are stuck together and you can't really separate them, or the moment one moves the other goes flying off into the distance because of the collision physics.

**Comment by JAWolfe04** [comment]
I've been using this in my addon and I've yet to have any issues with it. It actually works better than expected. If you want to test the behavior for yourself, just grab a spawn egg and spam right-click on a block. I thought I should suggest this since it is such a simple fix that works great and fixes an annoying problem.
