### ISSUE TITLE
Crash on EntityPlayerMP

### ISSUE THREAD

**Issue by lightning02** [Deadrik/TFCraft#822]
http://pastebin.com/hptRqdPT
Hello, I was sure all was fine but.. well, I was wrong. :/
A crash due to EntityPlayerMP when creating a new world, this does not occur if you run a forge server then log-in in the world..
This doesn't even happen on thermos server if you add -noverify argument in the start-file.bat
Is there something I could do to fix it? or should I just remove some particular mod?
You can check the logs on dropbox without the need to download it :)
https://www.dropbox.com/s/xka2dlddof3zcdz/fml-client-latest.log?dl=0
https://www.dropbox.com/s/47ym3f9dyzcioka/latest.log?dl=0

**Comment by Kittychanley** [comment]
We do not offer support for Cauldron. Thermos is just another version of Cauldron. This is not a bug with TFC, it is a bug with Cauldron.

**Comment by lightning02** [comment]
excuse me, it happens when I create a single player world, then it reflect the same error when joining a world on a server with thermos, but doesn't occur with a forge server (those about what happen on servers side was just additional information, the problem is that when you create a single player world it crash this way)

**Comment by Kittychanley** [comment]
The "MP" part of EntityPlayerMP literally stands for multiplayer, so it's something sever-side causing the crash, even if it's just a server plugin you installed on single player. I took a look at the log again and you have so much stuff installed it could be any one of them causing the crash, especially considering that TFC isn't compatible with a lot of other mods. Anything you have installed that adds armor, weapons, mobs, food, ore generation, other dimensions, etc will not work properly unless you have added third party mods/add-ons made for filling in the gaps and editing configs.

**Comment by lightning02** [comment]
Thanks alot! :)
I don't know why it blame entityplayermp, I have no worldedit or other direct plugin on client side :/
It's pretty weird, I know

**Comment by Kittychanley** [comment]
Did you check to see if it even was TFC that's causing the crash? The log didn't look like it had anything specific saying it was TFC. Have you tried uninstalling TFC and everything dependent on it? If your game still crashes then it's not a problem with TFC and you need to get support from somebody else. If it doesn't crash, try putting just TFC back and not everything dependent on it. If it doesn't crash at that point then the problem is with one the mods dependent on TFC and you need to contact them for support.

**Comment by lightning02** [comment]
I removed every tfc addon, but the problem seems to persist
I also removed tfc itself and the game started
 maybe is some weird dynamic between tfc and one of the mods installed ?

**Comment by Kittychanley** [comment]
Most likely, however you have so many mods installed there's no easy way to quickly find which one is the problem. Even if you do find the one that's causing this crash, you're probably going to still have other crashes and bugs. You need to get rid of any mod that you added specifically for new dimensions. Any mod you added for the mobs you'll need get rid of unless you have something installed to scale the damage they do and health they have. Any mod you added for food you'll need to remove because you won't be able to eat it. Armor from any other mods will be useless. Remove mods you have for making ore generate, because TFC has a config file specifically for that. The list goes on, TFC really is not meant to be in super large tech packs with lots of other mods.

**Comment by Egorpom** [comment]
Only TFC and crash:
[crashlog](http://pastebin.com/xYgTXFUu)
[Look  this please](https://github.com/CyberdyneCC/Thermos/issues/431)

**Comment by Kittychanley** [comment]
@Egorpom As I stated before, and has been stated multiple times, TFC does not support Cauldron, and therefore does not support Thermos. Our ASM works just fine with forge, we're not going to alter it and have to different variations depending on whether or not it's a normal forge or a cauldron server.

**Comment by Egorpom** [comment]
@Kittychanley Ok. Thanks for reply.

**Comment by lightning02** [comment]
@Egorpom Try to add -noverify argument right after -java in your server starting.bat or whatever is called;
this issue should be solved this way with thermos but you will may still have singleplayer issue like me :l

**Comment by Portalboy** [comment]
Commenting here in hopes this will rank higher in google. Adding -noverify to my launch script fixed this for me as well. Thanks a lot @lightning02, I've spent the better part of 2 days looking for a solution to this.

I'll be researching the -noverify flag to see what potential side-effects it may have.
